#!/bin/sh
echo "-------------------------------------------------"
echo "GUTILS - $GUTILS_VERSION - NetCDF to ERDDAP Watch"
echo "-------------------------------------------------"
exec gutils_netcdf_to_erddap_watch
